name: BravoKits
main: bravopvp.plugins.kitpvp.BravoKits
author: Twisted_Panda
version: 1.0
commands:
  hulk:
  lol:
  tamer:
  ninja:
  ghost:
  kangaroo:
  fisherman:
  pikachu:
  kit:
   aliases: [kits, kitlist]
  archer:
  shop:
  pvp: